# Generated by Django 4.0.3 on 2022-04-06 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='copy_borrowed',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
