# Generated by Django 4.0.3 on 2022-04-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_alter_book_detail_copy_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='copy_borrowed',
            field=models.SmallIntegerField(default=0),
        ),
    ]
